### ISSUE TITLE
Chrome provider

### ISSUE THREAD

**Issue by klauskkj10** [zachey01/gpt4free.js#13]
Can you give an example of how to use Chrome provider?

**Comment by zachey01** [comment]
const messages = [{ role: "user", content: "hi!" }];
const options = {
  provider: "Chrome",
};

(async () => {
  const provider = GPT4js.createProvider(options.provider);
  try {
    const text = await provider.chatCompletion(messages, options, (data) => {
      console.log(data);
    });
    console.log(text);
  } catch (error) {
    console.error("Error:", error);
  }
})();

**Comment by klauskkj10** [comment]
In Chrome.js

```"use strict";
import Provider from "./provider.js";

class ChromeProvider extends Provider {
  async chatCompletion(messages) {
    let message = messages[0].content;
    const aiObj = ai.createTextSession();
    const promptInt = await aiObj;
    let response = await promptInt.prompt(message);
    return response;
  }
}

export default ChromeProvider;```

It is returning ai is not defined
