### ISSUE TITLE
Gpt 4o-free

### ISSUE THREAD

**Issue by klauskkj10** [zachey01/gpt4free.js#2]
Está versão do gpt tem um limite de uso? Está dando erro no meu da noite pro dia...

**Comment by klauskkj10** [comment]
? Is there a usage limit? My gpt-4o-free is not working

**Comment by klauskkj10** [comment]
? Is there a usage limit? My gpt-4o-free is not working

**Comment by zachey01** [comment]
Add `use_proxy: true` to options

**Comment by klauskkj10** [comment]
I used it but it didn't solve the problem, it just gives me the error "Network response was not ok". I didn't have this problem yesterday... And this isn't happening in gpt-4, only in gpt-4o-free, which I want to use

**Comment by zachey01** [comment]
try this 
```js
const options = {
  provider: "ChatBotRu",
  model: "gpt-4o",
};
```

**Comment by Abba710** [comment]
I am encountering the following error when attempting to use the models gpt-4o-free, gpt-4o, and gpt-4:
`Network response error Resource_exhausted: Rate limit exceeded for model; try again in about an hour.`
However, I have not used these models on the Nextway provider recently, so I don’t understand why I am hitting a rate limit. Additionally, I sometimes receive a "Network response error" message instead, which adds to the confusion.
