### ISSUE TITLE
Not able to perform webSearch

### ISSUE THREAD

**Issue by OFFICIAL-DARK-BEAST** [zachey01/gpt4free.js#5]
![image](https://github.com/user-attachments/assets/12ef0ab8-e12d-4c67-98f4-6f92f3505174)
![image](https://github.com/user-attachments/assets/50b4e06f-ff67-4801-ad79-8c7d7cc60833)

**Comment by OFFICIAL-DARK-BEAST** [comment]
And also ChatBotRu not working:

![image](https://github.com/user-attachments/assets/10274272-378e-4bd6-b104-42290aa09bee)
![image](https://github.com/user-attachments/assets/9681def8-cb79-42ed-8754-ae8e1af8a44d)

**Comment by OFFICIAL-DARK-BEAST** [comment]
Also kindly share docs or example code for image generation

**Comment by zachey01** [comment]
webSearch only works fully through `BlackBox`, in `Nextway` sometimes. ChatBotRu stopped working

**Comment by OFFICIAL-DARK-BEAST** [comment]
Oh I see. Can you show a sample code for image generation?

**Comment by OFFICIAL-DARK-BEAST** [comment]
And also is it possible to share images in base64 format to gpt4o?

**Comment by zachey01** [comment]
> Oh I see. Can you show a sample code for image generation?

```js
const options = {
  provider: "DALLE2",
};

(async () => {
  const provider = GPT4js.createProvider(options.provider);
  try {
    const base64 = await provider.imageGeneration("wood", options);
    console.log(base64);
  } catch (error) {
    console.error("Error:", error);
  }
})();
```

**Comment by zachey01** [comment]
> And also is it possible to share images in base64 format to gpt4o?

Nextway doesn't support this

**Comment by OFFICIAL-DARK-BEAST** [comment]
Oh I see. Thank you :)
