### ISSUE TITLE
Problem sending large responses

### ISSUE THREAD

**Issue by klauskkj10** [zachey01/gpt4free.js#6]
When the text is large, like an essay or a large code, I receive the following return:

ChatBotRu:
SyntaxError: Unexpected token 'T', "The space "... is not valid JSON

Large texts:
SyntaxError: Unexpected token '_', "_{"code":2"... is not valid JSON

Any ideas to get around the error?

**Comment by zachey01** [comment]
ChatBotRu has stopped working. 
up to 4096 tokens are supported

**Comment by klauskkj10** [comment]
How to get around this large response error? Is there any setting to limit tokens or some other way to avoid the error?
