### ISSUE TITLE
> provideby[EasCht](:/.qngc)

### ISSUE THREAD

**Issue by ActBotArt** [zachey01/gpt4free.js#8]
dimmi come rimuovere quando stream:true fine > provideby[EasCht](:/.qngc)

**Comment by ActBotArt** [comment]
let options = {provider:"Nextway",model:"llama-3.1-405b-instruct-free",webSearch:true,stream:stream}; 
const provider = GPT4js.createProvider(options.provider);  
const fullText = await provider.chatCompletion(messages, options, (data) => {
console.log(`data: ${data}`);
});

**Comment by zachey01** [comment]
try this `fullText.replace(/> pr.*$/, '');`

**Comment by ActBotArt** [comment]
> Попробуйте это `fullText.replace(/> pr.*$/, '');`

![image](https://github.com/user-attachments/assets/8cc4b5b6-41bb-44d5-a58c-8d2efed48e0a)
Unfortunately it doesn't work that way

**Comment by zachey01** [comment]
Исправил
